name: Github actions Repository

on: push
jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
       
        with:
          python-version: '3.8.6'
      # Install PyTest and Flask
      - name: Install Dependencies
        run: pip install -r requirements.txt
      # Run the tests
      - name: Run tests
        run: pytest
     
       - name: Copy repository contents to vps via scp
        uses: appleboy/scp-action@master
        env:
          HOST: '${{ secrets.SSH_HOST }}'
          USERNAME: '${{ secrets.SSH_USER }}'
          PORT: '${{ secrets.PORT }}'
          KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
        with:
          source: .
          target: /home/Zafar_Final_CD_Assignment-01/
          
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SSH_HOST }}'
          USERNAME: '${{ secrets.SSH_USER }}'
          PORT: '${{ secrets.PORT }}'
          KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
          script: sh /home/Zafar_Final_CD_Assignment-01/commands.sh

